package com.dalai.par;

import java.util.HashMap;
import java.util.Map;

//389. Find the Difference
public class FindTheDifference {

	/*
	 * Given two strings s and t which consist of only lowercase letters.
	 * 
	 * String t is generated by random shuffling string s and then add one more
	 * letter at a random position.
	 * 
	 * Find the letter that was added in t.
	 */
	public char findTheDifference(String s, String t) {

		Map<Character, Integer> map = new HashMap<>();

		for (int i = 0, len = s.length(); i < len; i++) {
			map.put(s.charAt(i), map.getOrDefault(s.charAt(i), 0) + 1);
		}
		for (int i = 0, len = t.length(); i < len; i++) {
			if (map.containsKey(t.charAt(i)) && map.get(t.charAt(i)) > 0) {
				map.put(t.charAt(i), map.getOrDefault(t.charAt(i), 0) - 1);
			} else {
				return t.charAt(i);
			}
		}
		return 0;
	}
}
